name: deploy_test

on:
  push:
    branches: [ test ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_TEST }}
          username: ${{ secrets.SERVER_USERNAME_TEST }}
          key: ${{ secrets.SERVER_KEY_TEST }}
          port: 22
          script: |
            ${{ secrets.SERVER_CLONE_SCRIPT_TEST }}
            echo "${{ secrets.SERVER_ENV_TEST }}" > .env.test
            npm run build
            npm run docker:test
            pm2 start ./ecosystem.config.js --env test
